import pathlib
import tempfile
import unittest

from testlib import load_script_module


run_pair = load_script_module("run_pair", "scripts/run_pair.py")


class RunPairTests(unittest.TestCase):
    def test_callgrind_metric_names_pair_old_and_new_output_roots(self) -> None:
        old = pathlib.Path("iai/sample/bench/callgrind.out.123")
        new = pathlib.Path("gungraun/sample/bench/callgrind.out.987")

        self.assertEqual(
            run_pair.normalize_callgrind_metric_name(old),
            run_pair.normalize_callgrind_metric_name(new),
        )
        self.assertEqual(
            run_pair.normalize_callgrind_metric_name(new),
            "gungraun/sample/bench/callgrind.out",
        )

    def test_collects_old_and_new_path_fixtures_under_same_metric_key(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = pathlib.Path(tmp)
            old = target / "iai" / "sample" / "callgrind.out.11"
            new = target / "gungraun" / "sample" / "callgrind.out.22"
            old.parent.mkdir(parents=True)
            new.parent.mkdir(parents=True)
            old.write_text("summary: 100\n", encoding="utf-8")
            new.write_text("summary: 110\n", encoding="utf-8")

            old_name = run_pair.normalize_callgrind_metric_name(
                old.relative_to(target)
            )
            new_name = run_pair.normalize_callgrind_metric_name(
                new.relative_to(target)
            )
            self.assertEqual(old_name, new_name)

    def test_detects_both_runner_family_version_mismatches(self) -> None:
        self.assertEqual(
            run_pair.runner_version_mismatch_family(
                "iai-callgrind-runner (0.16.0) is older than iai-callgrind (0.16.1)"
            ),
            "iai-callgrind",
        )
        self.assertEqual(
            run_pair.runner_version_mismatch_family(
                "gungraun-runner (0.19.3) is older than gungraun (0.19.4)"
            ),
            "gungraun",
        )

    def test_paired_totals_exclude_metrics_missing_from_either_revision(self) -> None:
        base_metrics = [
            {"metric": "existing", "value": 100},
            {"metric": "removed", "value": 250},
        ]
        head_metrics = [
            {"metric": "existing", "value": 110},
            {"metric": "added", "value": 500},
        ]

        self.assertEqual(
            run_pair.paired_metric_totals(base_metrics, head_metrics),
            (100.0, 110.0, 1),
        )

    def test_paired_totals_are_empty_when_no_metric_identity_is_shared(self) -> None:
        self.assertEqual(
            run_pair.paired_metric_totals(
                [{"metric": "old", "value": 100}],
                [{"metric": "new", "value": 100}],
            ),
            (0, 0, 0),
        )

    def test_loads_lifecycle_environment_without_shell_evaluation(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            environment_file = pathlib.Path(tmp) / "lifecycle.env"
            environment_file.write_text(
                "# generated by setup\n"
                "DATABASE_URL=postgres://localhost/bench?sslmode=disable\n"
                "export DISPLAY_NAME=benchmark service\n",
                encoding="utf-8",
            )

            self.assertEqual(
                run_pair.load_lifecycle_environment(environment_file),
                {
                    "DATABASE_URL": "postgres://localhost/bench?sslmode=disable",
                    "DISPLAY_NAME": "benchmark service",
                },
            )

            environment_file.write_text(
                "RUST_PR_BENCH_SIDE=spoofed\n", encoding="utf-8"
            )
            with self.assertRaisesRegex(ValueError, "may not override"):
                run_pair.load_lifecycle_environment(environment_file)

    def test_execution_runs_isolated_lifecycle_and_passes_setup_environment(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            workdir = root / "repository"
            target_dir = workdir / ".bench-target" / "head"
            log_dir = root / "artifacts"
            workdir.mkdir()

            result = run_pair.run_execution(
                """
                test "$BENCH_TOKEN" = "$RUST_PR_BENCH_SIDE"
                mkdir -p "$CARGO_TARGET_DIR/gungraun/fixture"
                printf 'summary: 100\\n' > "$CARGO_TARGET_DIR/gungraun/fixture/callgrind.out.1"
                """,
                workdir,
                target_dir,
                "gungraun",
                "mean",
                side="head",
                case_slug="service-default",
                repository=workdir,
                log_dir=log_dir,
                setup_command="""
                printf 'BENCH_TOKEN=%s\\n' "$RUST_PR_BENCH_SIDE" >> "$RUST_PR_BENCH_ENV_FILE"
                printf 'setup:%s\\n' "$RUST_PR_BENCH_EXECUTION_ID" >> "$RUST_PR_BENCH_REPOSITORY/events"
                """,
                readiness_command="""
                if [ ! -e "$CARGO_TARGET_DIR/ready" ]; then
                  touch "$CARGO_TARGET_DIR/ready"
                  exit 1
                fi
                test "$BENCH_TOKEN" = "$RUST_PR_BENCH_SIDE"
                """,
                teardown_command="""
                printf 'teardown:%s:%s\\n' "$RUST_PR_BENCH_SIDE" "$BENCH_TOKEN" >> "$RUST_PR_BENCH_REPOSITORY/events"
                """,
                readiness_timeout_seconds=1,
                readiness_retry_interval_seconds=0.01,
            )

            self.assertEqual(result["total"], 100)
            self.assertFalse(result.get("error", False))
            self.assertEqual(result["lifecycle"]["setup"]["exit_code"], 0)
            self.assertEqual(result["lifecycle"]["readiness"]["attempts"], 2)
            self.assertEqual(result["lifecycle"]["teardown"]["exit_code"], 0)
            self.assertFalse((target_dir / "lifecycle.env").exists())
            self.assertTrue((log_dir / "head.setup.log").is_file())
            self.assertTrue((log_dir / "head.readiness.log").is_file())
            self.assertTrue((log_dir / "head.teardown.log").is_file())
            events = (workdir / "events").read_text(encoding="utf-8")
            self.assertIn("setup:", events)
            self.assertIn("teardown:head:head", events)

    def test_teardown_runs_after_benchmark_failure(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            workdir = root / "repository"
            target_dir = workdir / ".bench-target" / "base"
            workdir.mkdir()

            result = run_pair.run_execution(
                "printf 'compilation failed' >&2; exit 7",
                workdir,
                target_dir,
                "criterion",
                "mean",
                side="base",
                case_slug="service-default",
                repository=workdir,
                log_dir=root / "artifacts",
                setup_command=(
                    "printf 'SERVICE_NAME=fixture\\n' >> \"$RUST_PR_BENCH_ENV_FILE\""
                ),
                teardown_command=(
                    "printf 'teardown:%s\\n' \"$SERVICE_NAME\" >> "
                    "\"$RUST_PR_BENCH_REPOSITORY/events\""
                ),
            )

            self.assertTrue(result["error"])
            self.assertEqual(result["error_code"], 7)
            self.assertEqual(result["error_stage"], "benchmark")
            self.assertIn("compilation failed", result["error_output"])
            self.assertEqual(result["lifecycle"]["teardown"]["exit_code"], 0)
            self.assertEqual(
                (workdir / "events").read_text(encoding="utf-8"),
                "teardown:fixture\n",
            )

    def test_teardown_runs_after_setup_failure_with_partial_environment(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            workdir = root / "repository"
            target_dir = workdir / ".bench-target" / "head"
            workdir.mkdir()

            result = run_pair.run_execution(
                "touch benchmark-ran",
                workdir,
                target_dir,
                "criterion",
                "mean",
                side="head",
                case_slug="service-default",
                repository=workdir,
                log_dir=root / "artifacts",
                setup_command=(
                    "printf 'SERVICE_NAME=partial\\n' >> \"$RUST_PR_BENCH_ENV_FILE\"; "
                    "printf 'setup failed' >&2; exit 3"
                ),
                teardown_command=(
                    "printf 'teardown:%s\\n' \"$SERVICE_NAME\" >> "
                    "\"$RUST_PR_BENCH_REPOSITORY/events\""
                ),
            )

            self.assertTrue(result["error"])
            self.assertEqual(result["error_code"], 3)
            self.assertEqual(result["error_stage"], "setup")
            self.assertFalse((workdir / "benchmark-ran").exists())
            self.assertEqual(
                (workdir / "events").read_text(encoding="utf-8"),
                "teardown:partial\n",
            )

    def test_readiness_timeout_is_reported_and_still_runs_teardown(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            workdir = root / "repository"
            workdir.mkdir()

            result = run_pair.run_execution(
                "touch benchmark-ran",
                workdir,
                workdir / ".bench-target" / "head",
                "criterion",
                "mean",
                side="head",
                case_slug="service-default",
                repository=workdir,
                log_dir=root / "artifacts",
                readiness_command="printf 'not ready' >&2; exit 1",
                teardown_command="touch teardown-ran",
                readiness_timeout_seconds=0.03,
                readiness_retry_interval_seconds=0.005,
            )

            self.assertTrue(result["error"])
            self.assertEqual(result["error_code"], 124)
            self.assertEqual(result["error_stage"], "readiness")
            self.assertIn("timed out", result["error_reason"])
            self.assertGreaterEqual(result["lifecycle"]["readiness"]["attempts"], 1)
            self.assertTrue((workdir / "teardown-ran").is_file())
            self.assertFalse((workdir / "benchmark-ran").exists())


if __name__ == "__main__":
    unittest.main()
